# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e136e1255f729778ba3375cc15e8d077e52f2ec641109ce256e75c41ea7e12de74a32c5ef36ab19437d2fb417d797ebaeec62cd214ebb265a3f2720fc00aea0

test:
  secret_key_base: 1527cd83f61fdbc65595729f14932b642c8f4be0938a6ad70fc95ffbdf70f5d83e9b285de0881cf27927c1f84ce2ed55ba31b310e6b7caf25e7e529f09647068

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
